### ISSUE TITLE
Minor UX Issue and Extension Errors

### ISSUE THREAD

**Issue by riongull** [readme55/Dash-Chrome-Wallet#2]
**UX issue:** 
I clicked "create wallet" but didn't get any feedback whether it worked or not.  The button text turned gray and is very hard to read now.
Should there be an address in the text area now if it worked, because I don't see anything there still (pressed "create wallet" a few times).
I clicked the extension icon a couple times to hide and reshow the UI.  Now there's an address there.

**Extension Errors:**
After doing the above, I checked the extensions tab and found an Error notification:
![Screen Shot 2020-04-04 at 13 35 43](https://user-images.githubusercontent.com/6496310/78459909-c0716a00-7679-11ea-999b-f91aaa80cfe6.png)

Clicking through the button yields these errors:
![Screen Shot 2020-04-04 at 13 35 01](https://user-images.githubusercontent.com/6496310/78459919-d67f2a80-7679-11ea-9cd9-98e562ee3659.png)

**Comment by readme55** [comment]
Thanks for feedback! Just pushed a new release and UX Issues are fixed.
Extension errors might still come up, but it depends from the dashjs library - so need to wait for an update there. So gonna close this issue.
